### ISSUE TITLE
Not sold separately not sticking

### ISSUE THREAD

**Issue by wynterb** [helgatheviking/wc-not-sold-separately#5]
I'm using Mix and Match plugin  and I can select the Not Sold Separately on the variation, which does remove the variation from the product page, but while the product can be selected from the Mix and Match, it doesn't add it to the cart? Progressing to the Cart gives an error "Sorry, the configuration for "The Select Six Case" is no longer valid. Please edit your cart and try again." When I go to edit the product the Not Sold Separately is now deselected?
Thanks for any thoughts!
![Screenshot 2023-12-19 at 10 09 13](https://github.com/kathyisawesome/wc-not-sold-separately/assets/10373497/3041d400-5c08-44de-9572-7fc24e4a364e)
![Screenshot 2023-12-19 at 10 10 12](https://github.com/kathyisawesome/wc-not-sold-separately/assets/10373497/e75a4bf8-f1ba-42f4-876d-c0c2ce0d0f82)

**Comment by helgatheviking** [comment]
Hi thanks for reporting. Can you post your system status as a code block (so use three backticks)?

**Comment by wynterb** [comment]
```

`
### WordPress Environment ###

WordPress address (URL): https://lhj.gyro-build.uk
Site address (URL): https://lhj.gyro-build.uk
WC Version: 8.4.0
REST API Version: ✔ 8.4.0
WC Blocks Version: ✔ 11.6.2
Action Scheduler Version: ✔ 3.7.0
Log Directory Writable: ✔
WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 8.2.13
PHP Post Max Size: 512 MB
PHP Time Limit: 120
PHP Max Input Vars: 8000
cURL Version: 7.87.0
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB-cll-lve-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.4.0
WC Database Prefix: wp_
Total Database Size: 80.70MB
Database Data Size: 53.76MB
Database Index Size: 26.94MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.23MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 2.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.45MB + Index: 0.61MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.39MB + Index: 0.31MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
wp_csp3_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cspv5_pages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 7.45MB + Index: 0.22MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 11.42MB + Index: 9.03MB + Engine InnoDB
wp_posts: Data: 3.52MB + Index: 0.67MB + Engine InnoDB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_analytics_ga: Data: 0.30MB + Index: 0.25MB + Engine InnoDB
wp_rank_math_analytics_gsc: Data: 3.52MB + Index: 5.98MB + Engine InnoDB
wp_rank_math_analytics_inspections: Data: 0.28MB + Index: 0.11MB + Engine InnoDB
wp_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_analytics_objects: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sp_domain_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_trustindex_tripadvisor_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wcpl_user_packages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_mnm_child_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
wp_wc_order_stats: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.48MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.41MB + Index: 0.16MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_role_counts: Data: 0.00MB + Index: 0.00MB + Engine MEMORY
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsecurityevents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfwaffailures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wml_entries: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgb_cards: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_wpgb_facets: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wpgb_grids: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpgb_index: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_wpml_mails: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.23MB + Index: 0.13MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.11MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

acf-field: 24
acf-field-group: 2
ae_global_templates: 1
attachment: 1549
custom_css: 2
customize_changeset: 4
e-landing-page: 4
elementor_library: 38
groovy_menu_preset: 1
jet-smart-filters: 6
ldh-notes: 1
nav_menu_item: 46
oembed_cache: 7
page: 38
post: 95
product: 112
product_variation: 167
revision: 190
seedprod: 2
shop_coupon: 2
shop_order: 794
shop_order_refund: 10
wp_block: 1
wp_global_styles: 1
wp_navigation: 1
wpcode: 16

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Advanced Custom Fields PRO: by WP Engine – 6.2.4
Elementor Pro: by Elementor.com – 3.18.1
Elementor: by Elementor.com – 3.18.2
WPCode Lite: by WPCode – 2.1.6
WP Tripadvisor Review Widgets: by Trustindex.io  – 11.2.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.23.14.0

Not Sold Separately for WooCommerce: by Kathy Darling – 2.1.0
WooCommerce Mix and Match Products: by Kathy Darling – 2.6.1
WooCommerce: by Automattic – 8.4.0
Wordfence Security: by Wordfence – 7.11.0
WP Grid Builder - Elementor: by Loïc Blascos – 1.2.6
WP Grid Builder: by Loïc Blascos – 1.8.1
WP-Optimize Premium - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.22


### Inactive Plugins (2) ###

Mailchimp for WooCommerce: by Mailchimp – 3.5
WooCommerce Google Analytics Integration: by WooCommerce – 1.8.11

### Must Use Plugins (1) ###

WordPress automation by Installatron: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #7321 - /shop/
Cart: #1110 - /cart/
Checkout: #7323 - /checkout/
My account: #7324 - /my-account/
Terms and conditions: #6682 - /website-terms-and-conditons/

### Theme ###

Name: Lawsons Dry Hills
Version: 1.0.1
Author URL: https://www.gyroscopegroup.co.uk/
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.9.0
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: lawsons-dry-hills/woocommerce/emails/customer-new-account.php
lawsons-dry-hills/woocommerce/emails/customer-on-hold-order.php
lawsons-dry-hills/woocommerce/emails/customer-processing-order.php
lawsons-dry-hills/woocommerce/emails/customer-reset-password.php


### Mix and Match Products ###

Version: 2.6.1
Database Version: 2.6.1
Template Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-19 15:30:28 +13:00
Options: ✔
Notes: 138
Onboarding: completed

### Action Scheduler ###

Cancelled: 16
Oldest: 2023-12-07 18:03:47 +1300
Newest: 2023-12-07 18:03:47 +1300

Complete: 1,142
Oldest: 2023-11-23 17:52:45 +1300
Newest: 2023-12-19 23:08:07 +1300

Failed: 281
Oldest: 2022-11-07 03:56:54 +1300
Newest: 2023-12-14 18:19:51 +1300

Pending: 1
Oldest: 2023-12-20 03:36:41 +1300
Newest: 2023-12-20 03:36:41 +1300


### Status report information ###

Generated at: 2023-12-20 01:14:20 +13:00
`

```

**Comment by wynterb** [comment]
Thanks! – Am newbie with github so hope that’s correct!

Wynter Blathwayt • CREATIVE DIRECTOR
Gyroscope London Ltd
[signature_1276319641] +44-7515-953905<tel:+44-7515-953905>  [signature_4114481574] +44-20-81448694<tel:+44-20-81448694>
[signature_3593488476] ***@***.******@***.***>  [signature_63708903] gyroscopegroup.co.uk
[signature_3851010426]<https://www.gyroscopegroup.co.uk/>
[signature_2048877165]<https://www.facebook.com/GyroscopeLDN/> [signature_2695837136] <https://twitter.com/GyroscopeGRP/>  [signature_692485347] <https://www.instagram.com/GyroscopeGRP/>  [signature_915470465] <https://www.linkedin.com/in/wynterblathwayt/>
Gyroscope London LTD. Registered in England and Wales: 08919050


From: Kathy ***@***.***>
Date: Tuesday, 19 December 2023 at 11:13
To: kathyisawesome/wc-not-sold-separately ***@***.***>
Cc: Wynter Blathwayt ***@***.***>, Author ***@***.***>
Subject: Re: [kathyisawesome/wc-not-sold-separately] Not sold separately not sticking (Issue #5)

Hi thanks for reporting. Can you post your system status as a code block (so use three backpacks)?

**Comment by helgatheviking** [comment]
It is, thank you! I saw you replied in our help desk too.... I just wanted to know if you'd updated MNM before looking into this. But your above system status seems to confirm that. I'll see what I can find out.

**Comment by wynterb** [comment]
Ok thanks!  Amazing.

When I first installed it, it worked perfectly! My client was so happy and so I’m not sure what happened.

**Comment by helgatheviking** [comment]
Looks like you found a bug in the variations display. Should be fixed now.... Please try downloading:
https://github.com/kathyisawesome/wc-not-sold-separately/releases/download/2.2.0/wc-not-sold-separately-2.2.0.zip

**Comment by helgatheviking** [comment]
Oopps... hang on... found a small problem in the above.

**Comment by wynterb** [comment]
Incredible, thanks!  Will be able to check in an hour, but really appreciate you taking,  the time to solve my issue!

**Comment by helgatheviking** [comment]
ok, fixed my other issue. Should :crossed_fingers: work now.

**Comment by wynterb** [comment]
Back at my desk – removed and added the new version of the wc-not-sold-separately
Version 2.2.0
Mix and Match is at Version 2.6.1

Unfortunately still not working?

Shall I send you a admin invite



Wynter Blathwayt • CREATIVE DIRECTOR
Gyroscope London Ltd
[signature_1071486023] +44-7515-953905<tel:+44-7515-953905>  [signature_2265236870] +44-20-81448694<tel:+44-20-81448694>
[signature_3447033158] ***@***.******@***.***>  [signature_1924476170] gyroscopegroup.co.uk
[signature_3426126312]<https://www.gyroscopegroup.co.uk/>
[signature_2237470667]<https://www.facebook.com/GyroscopeLDN/> [signature_3826700606] <https://twitter.com/GyroscopeGRP/>  [signature_3302447823] <https://www.instagram.com/GyroscopeGRP/>  [signature_787987721] <https://www.linkedin.com/in/wynterblathwayt/>
Gyroscope London LTD. Registered in England and Wales: 08919050


From: Kathy ***@***.***>
Date: Tuesday, 19 December 2023 at 13:53
To: kathyisawesome/wc-not-sold-separately ***@***.***>
Cc: Wynter Blathwayt ***@***.***>, Author ***@***.***>
Subject: Re: [kathyisawesome/wc-not-sold-separately] Not sold separately not sticking (Issue #5)

ok, fixed my other issue. Should 🤞 work now.

**Comment by wynterb** [comment]
Not sure if its possible but can I revisit an issues with the Mix and Match plugin - Not Sold Separately: Im not getting messages to say "Temporarily Unavailable" on the Mix and Match product - see screenshot. 
![Screenshot 2024-05-23 at 16 48 26](https://github.com/kathyisawesome/wc-not-sold-separately/assets/10373497/689e6f80-ecd7-441a-9805-4ccead943b9f)

Cheers
Wynter

**Comment by helgatheviking** [comment]
Do you have the latest version of mnm (2.7.1 I think) and the latest of this? Some tweaks were made to not throw notices on php8.2

**Comment by wynterb** [comment]
Yes - and I have the latest update of Not Sold Separately - see attachment - all of these products should be available so Im not sure - its quite possibly user error!

![Screenshot 2024-05-24 at 13 35 00](https://github.com/kathyisawesome/wc-not-sold-separately/assets/10373497/e5250277-1dd5-47e5-96a8-0850cd22104b)

**Comment by helgatheviking** [comment]
the latest of Not Sold Separately is [2.4.0](https://github.com/kathyisawesome/wc-not-sold-separately/releases/download/2.4.0/wc-not-sold-separately-2.4.0.zip) which includes the fixes for php 8.2 compat. Your screenshot shows 2.3-beta1. Can you try updating and lemme know if you still have an issue?

**Comment by wynterb** [comment]
Perfect! Thanks _ I wonder why mine was saying it was a latest version - thanks for your help!

**Comment by helgatheviking** [comment]
Probably because this plugin doesn't serve any updates on its own to the WP dashboard like we're used to seeing. I attempted to add support for that via [Git Updater](https://git-updater.com/) so you could try installing the free version of that. 

I'd like a better solution though... except it needs to be very very easy for me (unlike WordPress.org's repo).

**Comment by wynterb** [comment]
ok.. now I know its tricky Ill make a note to look here if anything isn't working!

**Comment by helgatheviking** [comment]
Just found you can watch this repo for releases:

On the main page, go to "Watch" button, select "Custom" and then "Releases". Then click "Apply". In theory, that should tell you when a new version is deployed.

![image](https://github.com/kathyisawesome/wc-not-sold-separately/assets/507025/3d213ff7-fb2c-44ba-af1f-3920cbbdfed9)

**Comment by wynterb** [comment]
Hi Kathy – after what seems like  lifetime -  my customers have finally decided to move ahead with WooCommerce Mix and Match Products which I’ve been running on a test site for them and you installed Not Sold Separately for WooCommerce on that site for me to make the plugin work.

Now they’ve decided they want it on their live shop site – what’s the best way of adding the plugins to the live site? I can presumably disconnect the WooCommerce Mix and Match Products from the test site which is current until December, install the plugin on the live Domain and then reconnect the licence?

With the NSSfW plugin should I just grab a fresh copy from somewhere? Do I need to do anything else?

Cheers

Wynter

Wynter Blathwayt
CREATIVE DIRECTOR Gyroscope London Ltd
[https://www.gyroscopegroup.co.uk/emailimages/logo.png]<https://www.gyroscopegroup.co.uk/>
m. +44-7515-953905<tel:+44-7515-953905>  p. +44-0208-81448694<tel:+44-0208-81448694>
e. ***@***.******@***.***>  w. gyroscopegroup.co.uk<http://gyroscopegroup.co.uk>
[Facebook]<https://www.facebook.com/GyroscopeLDN/> [Twitter] <https://twitter.com/GyroscopeGRP/>  [Instagram] <https://www.instagram.com/GyroscopeGRP/>  [LinkedIn] <https://www.linkedin.com/in/wynterblathwayt/>
Gyroscope London LTD. Registered in England and Wales: 08919050


From: Kathy ***@***.***>
Date: Friday, 24 May 2024 at 14:12
To: kathyisawesome/wc-not-sold-separately ***@***.***>
Cc: Wynter Blathwayt ***@***.***>, Author ***@***.***>
Subject: Re: [kathyisawesome/wc-not-sold-separately] Not sold separately not sticking (Issue #5)

the latest of Not Sold Separately is 2.4.0<https://github.com/kathyisawesome/wc-not-sold-separately/releases/download/2.4.0/wc-not-sold-separately-2.4.0.zip> which includes the fixes for php 8.2 compat. Your screenshot shows 2.3-beta1. Can you try updating and lemme know if you still have an issue?

**Comment by helgatheviking** [comment]
Hi @wynterb nterb You can download the latest tagged version on the [Releases](https://github.com/kathyisawesome/wc-not-sold-separately/releases) page. No license is required for this.

As for Mix and Match itself, if you want to use the same license, you will need to disconnect your site from woocommerce.com and then reconnect the new site. You can [contact support](https://woocommerce.com/my-account/contact-support/) with a question about how to "manage your woocommerce.com account" if you get stuck.

**Comment by wynterb** [comment]
Thanks!

For somereason the layouts changed moving to the live site, but Im working on them now using Elementor templates

Do you know how to make the mobile version – it seems to be forcing a 2 column layout when I want it to swirch to single columns:
https://lawsonsdryhills.co.nz/product/pick-mix/

Cheers

Wyntert

Wynter Blathwayt
CREATIVE DIRECTOR Gyroscope London Ltd
[https://www.gyroscopegroup.co.uk/emailimages/logo.png]<https://www.gyroscopegroup.co.uk/>
m. +44-7515-953905<tel:+44-7515-953905>  p. +44-0208-81448694<tel:+44-0208-81448694>
e. ***@***.******@***.***>  w. gyroscopegroup.co.uk<http://gyroscopegroup.co.uk>
[Facebook]<https://www.facebook.com/GyroscopeLDN/> [Twitter] <https://twitter.com/GyroscopeGRP/>  [Instagram] <https://www.instagram.com/GyroscopeGRP/>  [LinkedIn] <https://www.linkedin.com/in/wynterblathwayt/>
Gyroscope London LTD. Registered in England and Wales: 08919050


From: Kathy ***@***.***>
Date: Tuesday, 13 August 2024 at 00:21
To: kathyisawesome/wc-not-sold-separately ***@***.***>
Cc: Wynter Blathwayt ***@***.***>, Mention ***@***.***>
Subject: Re: [kathyisawesome/wc-not-sold-separately] Not sold separately not sticking (Issue #5)

Hi @wynterb<https://github.com/wynterb> nterb You can download the latest tagged version on the Releases<https://github.com/kathyisawesome/wc-not-sold-separately/releases> page. No license is required for this.

As for Mix and Match itself, if you want to use the same license, you will need to disconnect your site from woocommerce.com and then reconnect the new site. You can contact support<https://woocommerce.com/my-account/contact-support/> with a question about how to "manage your woocommerce.com account" if you get stuck.

**Comment by helgatheviking** [comment]
Would mine opening a support ticket? We'll be happy to help you. https://woocommerce.com/my-account/contact-support/

**Comment by wynterb** [comment]
Thanks – Actually Ive asked the client to approve as it is because they’ve added way too much Short Description so Ive turned off the Short description so the 2 column works not to bad for now. If they come back Ill open a tricket

Wynter Blathwayt
CREATIVE DIRECTOR Gyroscope London Ltd
[https://www.gyroscopegroup.co.uk/emailimages/logo.png]<https://www.gyroscopegroup.co.uk/>
m. +44-7515-953905<tel:+44-7515-953905>  p. +44-0208-81448694<tel:+44-0208-81448694>
e. ***@***.******@***.***>  w. gyroscopegroup.co.uk<http://gyroscopegroup.co.uk>
[Facebook]<https://www.facebook.com/GyroscopeLDN/> [Twitter] <https://twitter.com/GyroscopeGRP/>  [Instagram] <https://www.instagram.com/GyroscopeGRP/>  [LinkedIn] <https://www.linkedin.com/in/wynterblathwayt/>
Gyroscope London LTD. Registered in England and Wales: 08919050


From: Kathy ***@***.***>
Date: Tuesday, 13 August 2024 at 13:09
To: kathyisawesome/wc-not-sold-separately ***@***.***>
Cc: Wynter Blathwayt ***@***.***>, Mention ***@***.***>
Subject: Re: [kathyisawesome/wc-not-sold-separately] Not sold separately not sticking (Issue #5)

Would mine opening a support ticket? We'll be happy to help you. https://woocommerce.com/my-account/contact-support/

**Comment by helgatheviking** [comment]
FYI.. if you go to the Customizer > WooCommerce > Mix and Match you can disable "enhanced mobile layout" (admittedly a bit opinionated) and you should get something like this:

![image](https://github.com/user-attachments/assets/e89a24a9-d32d-4981-bbd4-53e2c6fcf45d)

**Comment by wynterb** [comment]
Thanks so much – I’ll pass that on – I think they will want the bottles to display but I really appreciate the suggestion

Wynter Blathwayt
CREATIVE DIRECTOR Gyroscope London Ltd
[https://www.gyroscopegroup.co.uk/emailimages/logo.png]<https://www.gyroscopegroup.co.uk/>
m. +44-7515-953905<tel:+44-7515-953905>  p. +44-0208-81448694<tel:+44-0208-81448694>
e. ***@***.******@***.***>  w. gyroscopegroup.co.uk<http://gyroscopegroup.co.uk>
[Facebook]<https://www.facebook.com/GyroscopeLDN/> [Twitter] <https://twitter.com/GyroscopeGRP/>  [Instagram] <https://www.instagram.com/GyroscopeGRP/>  [LinkedIn] <https://www.linkedin.com/in/wynterblathwayt/>
Gyroscope London LTD. Registered in England and Wales: 08919050


From: Kathy ***@***.***>
Date: Tuesday, 13 August 2024 at 14:24
To: kathyisawesome/wc-not-sold-separately ***@***.***>
Cc: Wynter Blathwayt ***@***.***>, Mention ***@***.***>
Subject: Re: [kathyisawesome/wc-not-sold-separately] Not sold separately not sticking (Issue #5)

FYI.. if you go to the Customizer > WooCommerce > Mix and Match you can disable "enhanced mobile layout" (admittedly a bit opinionated) and you should get something like this:

image.png (view on web)<https://github.com/user-attachments/assets/e89a24a9-d32d-4981-bbd4-53e2c6fcf45d>
